services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    command: node dist/apps/api/src/main.js

  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    command: node dist/apps/calculator/src/main.js
